apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  environment: production

resources:
  - ../base

replicas:
  - name: service-one
    count: 4

patches:
  - target:
      kind: ConfigMap
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: production
